# Generated by Django 2.1 on 2018-08-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfertyDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builtyear', models.IntegerField()),
                ('roomnum', models.IntegerField()),
                ('bathnum', models.IntegerField()),
                ('garageplaces', models.IntegerField()),
            ],
            options={
                'db_table': 'oferty_d_b',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBBtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_bt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBEm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_b_em',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBEmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_em_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBFcm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_b_fcm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBFcmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_fcm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBGtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_gt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBGttName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_gtt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBHm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_b_hm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBHmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_hm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBMm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_b_mm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBMmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_mm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBRdtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_rdt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBRtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_rt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBSsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_ss_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDBTName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_b_t_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('builtyear', models.IntegerField()),
                ('roomnum', models.IntegerField()),
                ('floorno', models.IntegerField()),
                ('floornum', models.IntegerField()),
                ('rent', models.IntegerField()),
            ],
            options={
                'db_table': 'oferty_d_f',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbCm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_fb_cm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbCmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fb_cm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbFm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_fb_fm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbFmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fb_fm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbSName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fb_s_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbtLm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_fbt_lm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbtLmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fbt_lm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbtLtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fbt_lt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFBtName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_f_bt_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbWm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_fb_wm',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFbWmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_fb_wm_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFEm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'oferty_d_f_em',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFEmName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_f_em_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFFoName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_f_fo_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyDFHName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'oferty_d_f_h_name',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyEst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('data', models.DateField()),
                ('pow', models.IntegerField()),
                ('cena', models.IntegerField()),
                ('metr', models.BooleanField()),
                ('opis', models.TextField(blank=True)),
                ('stan', models.NullBooleanField()),
                ('kto', models.IntegerField(blank=True, null=True)),
                ('zdjecia', models.IntegerField(default='0')),
                ('pdf', models.IntegerField(blank=True, default='0', null=True)),
            ],
            options={
                'db_table': 'oferty_est',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyEstPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=30)),
                ('position', models.IntegerField(default='0')),
                ('width', models.IntegerField(default='0')),
                ('height', models.IntegerField(default='0')),
                ('thumbnail', models.NullBooleanField()),
                ('est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst')),
            ],
            options={
                'db_table': 'oferty_est_photo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyFpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst')),
            ],
            options={
                'db_table': 'oferty_fpage',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyMiasto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=25)),
                ('opis', models.CharField(blank=True, max_length=25)),
                ('prior', models.IntegerField()),
                ('grupa', models.IntegerField()),
                ('msc', models.CharField(max_length=25)),
                ('nazwa_otodom', models.CharField(max_length=25)),
                ('powiat', models.CharField(max_length=25)),
                ('nazwa_flat', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'oferty_miasto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyNazwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('name_de', models.CharField(max_length=50)),
                ('nazwa_poz', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'oferty_nazwa',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyOpisb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rok_bud', models.CharField(blank=True, max_length=350, null=True)),
                ('budulec', models.CharField(blank=True, max_length=350, null=True)),
                ('stan', models.CharField(blank=True, max_length=300, null=True)),
                ('dach', models.CharField(blank=True, max_length=350, null=True)),
                ('poddasze', models.CharField(blank=True, max_length=300, null=True)),
                ('piwnica', models.CharField(blank=True, max_length=300, null=True)),
                ('ogrzew', models.CharField(blank=True, max_length=300, null=True)),
                ('garaz', models.CharField(blank=True, max_length=350, null=True)),
                ('ogrodz', models.CharField(blank=True, max_length=350, null=True)),
                ('otoczenie', models.CharField(blank=True, max_length=300, null=True)),
                ('pow', models.IntegerField(blank=True, null=True)),
                ('parter', models.CharField(blank=True, max_length=350, null=True)),
                ('ip', models.CharField(blank=True, max_length=350, null=True)),
                ('stropy', models.CharField(blank=True, max_length=350, null=True)),
                ('elewacja', models.CharField(blank=True, max_length=350, null=True)),
                ('okna', models.CharField(blank=True, max_length=350, null=True)),
                ('drzwi', models.CharField(blank=True, max_length=350, null=True)),
                ('podlogi', models.CharField(blank=True, max_length=350, null=True)),
                ('sciany', models.CharField(blank=True, max_length=350, null=True)),
                ('gaz', models.CharField(blank=True, max_length=350, null=True)),
                ('woda', models.CharField(blank=True, max_length=350, null=True)),
                ('kan', models.CharField(blank=True, max_length=350, null=True)),
                ('est', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst')),
            ],
            options={
                'db_table': 'oferty_opisb',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyOpism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pietro', models.IntegerField(blank=True, null=True)),
                ('il_pie', models.IntegerField(blank=True, null=True)),
                ('stan', models.CharField(blank=True, max_length=150, null=True)),
                ('il_pok', models.IntegerField(blank=True, null=True)),
                ('wc', models.NullBooleanField()),
                ('wyp', models.CharField(blank=True, max_length=300, null=True)),
                ('wyp_dod', models.CharField(blank=True, max_length=300, null=True)),
                ('okna', models.CharField(blank=True, max_length=150, null=True)),
                ('sciany', models.CharField(blank=True, max_length=150, null=True)),
                ('podlogi', models.CharField(blank=True, max_length=150, null=True)),
                ('balkon', models.CharField(blank=True, max_length=150, null=True)),
                ('garaz', models.CharField(blank=True, max_length=150, null=True)),
                ('lok', models.CharField(blank=True, max_length=150, null=True)),
                ('ogrz', models.CharField(blank=True, max_length=150, null=True)),
                ('czynsz', models.CharField(blank=True, max_length=150, null=True)),
                ('est', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst')),
            ],
            options={
                'db_table': 'oferty_opism',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyRodzaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
                ('nazwa_msc', models.CharField(max_length=15)),
                ('nazwa_d', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'oferty_rodzaj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OfertyTyp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'oferty_typ',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='ofertyest',
            name='miasto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyMiasto'),
        ),
        migrations.AddField(
            model_name='ofertyest',
            name='nazwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyNazwa'),
        ),
        migrations.AddField(
            model_name='ofertyest',
            name='rodzaj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyRodzaj'),
        ),
        migrations.AddField(
            model_name='ofertyest',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyTyp'),
        ),
        migrations.AddField(
            model_name='ofertydfem',
            name='em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFEmName'),
        ),
        migrations.AddField(
            model_name='ofertydfem',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydfbwm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydfbwm',
            name='wm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbWmName'),
        ),
        migrations.AddField(
            model_name='ofertydfbtlm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydfbtlm',
            name='lm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbtLmName'),
        ),
        migrations.AddField(
            model_name='ofertydfbfm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydfbfm',
            name='fm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbFmName'),
        ),
        migrations.AddField(
            model_name='ofertydfbcm',
            name='cm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbCmName'),
        ),
        migrations.AddField(
            model_name='ofertydfbcm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='buildingtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFBtName'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='est',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='flatownership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFFoName'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='heating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFHName'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='locationtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbtLtName'),
        ),
        migrations.AddField(
            model_name='ofertydf',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbSName'),
        ),
        migrations.AddField(
            model_name='ofertydbmm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydbmm',
            name='mm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBMmName'),
        ),
        migrations.AddField(
            model_name='ofertydbhm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydbhm',
            name='hm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBHmName'),
        ),
        migrations.AddField(
            model_name='ofertydbfcm',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydbfcm',
            name='fcm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBFcmName'),
        ),
        migrations.AddField(
            model_name='ofertydbem',
            name='em',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBEmName'),
        ),
        migrations.AddField(
            model_name='ofertydbem',
            name='est',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='bt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBBtName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='est',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='gt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBGtName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='gtt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBGttName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='lt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbtLtName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='rdt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBRdtName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='rt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBRtName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='s',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDFbSName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='ss',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBSsName'),
        ),
        migrations.AddField(
            model_name='ofertydb',
            name='t',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyDBTName'),
        ),
    ]
