# Generated by Django 2.1 on 2018-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertymiasto',
            name='biuro',
            field=models.IntegerField(default=0),
        ),
    ]
