# Generated by Django 2.1 on 2018-08-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0002_ofertymiasto_biuro'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertydbbtname',
            name='name_gratka',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
