# Generated by Django 2.1.2 on 2018-11-01 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0004_auto_20181101_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ofertymiasto',
            name='biuro',
        ),
    ]
