# Generated by Django 2.1.2 on 2018-11-01 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0005_auto_20181101_0817'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfertyBiuro',
        ),
    ]
