# Generated by Django 2.1.2 on 2018-11-01 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0006_delete_ofertybiuro'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertyBiuro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel1', models.CharField(max_length=25, null=True)),
                ('tel2', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=25, null=True)),
            ],
            options={
                'managed': True,
                'db_table': 'oferty_biuro',
            },
        ),
        migrations.AddField(
            model_name='ofertymiasto',
            name='biuro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyBiuro'),
        ),
    ]
