# Generated by Django 2.1.2 on 2018-11-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0007_auto_20181101_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertybiuro',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
