# Generated by Django 2.1.2 on 2018-11-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0008_auto_20181101_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertybiuro',
            name='nazwisko',
            field=models.TextField(null=True),
        ),
    ]
