# Generated by Django 2.1.2 on 2018-12-03 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0011_ofertyest_kto_prowadzi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertyest',
            name='kto_prowadzi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='oferty.OfertyUsers'),
        ),
    ]
