# Generated by Django 2.1.7 on 2019-03-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0012_auto_20181203_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertyopisb',
            name='est',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst', verbose_name='numer oferty'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='garaz',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='garaż'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='ip',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='piętro'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='kan',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='kanalizacja'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='ogrodz',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ogrodzenie'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='ogrzew',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ogrzewanie'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='podlogi',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='podłogi'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='pow',
            field=models.IntegerField(blank=True, null=True, verbose_name='powierzchnia budynku'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='rok_bud',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='rok budowy'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='sciany',
            field=models.CharField(blank=True, max_length=350, null=True, verbose_name='ściany'),
        ),
        migrations.AlterField(
            model_name='ofertyopisb',
            name='stan',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='stan techniczny'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='est',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='oferty.OfertyEst', verbose_name='numer oferty'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='garaz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='garaż'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='il_pie',
            field=models.IntegerField(blank=True, null=True, verbose_name='ilość pięter w budynku'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='il_pok',
            field=models.IntegerField(blank=True, null=True, verbose_name='ilość pokoi'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='lok',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='lokalizacja'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='ogrz',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ogrzewanie'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='pietro',
            field=models.IntegerField(blank=True, null=True, verbose_name='piętro'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='podlogi',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='podłogi'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='sciany',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='ściany'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='stan',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='stan techniczny'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='wc',
            field=models.NullBooleanField(verbose_name='osobne wc'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='wyp',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='wyposażenie w cenie'),
        ),
        migrations.AlterField(
            model_name='ofertyopism',
            name='wyp_dod',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='wyposażenie dodatkowe'),
        ),
    ]
