# Generated by Django 2.2.5 on 2019-10-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0014_remove_ofertyest_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertyest',
            name='data_sprz',
            field=models.DateField(blank=True, null=True),
        ),
    ]
