# Generated by Django 2.2.11 on 2020-08-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0016_customoffer_customofferid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customoffer',
            name='token',
            field=models.CharField(max_length=16),
        ),
    ]
