# Generated by Django 2.2.11 on 2020-08-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0017_auto_20200802_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='customofferid',
            name='customoffer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='oferty.CustomOffer'),
            preserve_default=False,
        ),
    ]
