# Generated by Django 2.2.11 on 2020-08-02 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0018_customofferid_customoffer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomOfferId',
        ),
    ]
