# Generated by Django 2.2.11 on 2020-08-02 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0019_delete_customofferid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customoffer',
            name='offer_list',
            field=models.CharField(default=0, max_length=100, validators=[django.core.validators.int_list_validator]),
            preserve_default=False,
        ),
    ]
