# Generated by Django 2.2.11 on 2020-08-02 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0020_customoffer_offer_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customoffer',
            name='offer_list',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.int_list_validator]),
        ),
    ]
