# Generated by Django 2.2.11 on 2020-08-02 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferty', '0021_auto_20200802_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clipboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(max_length=16)),
                ('ip', models.GenericIPAddressField(null=True)),
                ('offer_list', models.CharField(max_length=150, unique=True, validators=[django.core.validators.int_list_validator])),
            ],
        ),
        migrations.DeleteModel(
            name='CustomOffer',
        ),
    ]
